### ISSUE TITLE
Many Apps do not have documentation

### ISSUE THREAD

**Issue by ManApart** [inhindsight/hindsight#207] opened 2020-04-03 11:40 UTC
Many apps have a 'todo' in their readme for documentation. This makes it harder for developers to grasp the context of an app without reading through all of it (and some of other apps') code.

We have a card for documenting modules and functions (#50), but even before we play that card we should have a top level description/document for the apps themselves.

**Comment by jdenen** [comment] 2020-04-03 13:38
Closing as duplicate of #49 

And that issue will be closed soon. My follow up to #188 is to document all our changes. Well, I'm documenting everything since I'm already there.

**Closed by jdenen** 2020-04-03 13:38 UTC
Labels: duplicate
